import React, { useContext } from "react";
import Head from "next/head";
import Header from "../components/header/Header";
import Hero from "../components/hero/Hero";
import ProductsDisplay from "../components/products/ProductsDisplay";
import products from "../utils/data.json";
import { ThemeContext } from "../context/ThemeContext";

import {confi} from "react-redux"

export default function Home() {
  const { isLightTheme, light, dark } = useContext(ThemeContext);
  const theme = isLightTheme ? light : dark;

  return (
    <div className="" style={{ color: theme.syntax, background: theme.bg }}>
      <Head>
        <title>Taaj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Hero />
        <ProductsDisplay products={products} />
      </main>
    </div>
  );
}

// importing data from the server

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props: {
      products,
    },
  };
}
